HACK: disable torch.multiprocessing.set_start_method()
When running `tox -e py3-e2e` in CI, I get

```
Error:     raise RuntimeError('context has already been set')
```

This ignores the error for the moment, but really needs to be looked
at again because this is not an acceptable change to merge.